<?php

namespace MessageBundle\Repository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    function countMessages(){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('count(message)');
        $qb->from('MessageBundle:Message','message')
            ->where('message.enabled = true');
        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;
    }
}
