promo_code:
    resource: "@PromoCodeBundle/Controller/"
    type:     annotation
    prefix:   /

collection:
    resource: "@CollectionBundle/Controller/"
    type:     annotation
    prefix:   /

order:
    resource: "@OrderBundle/Controller/"
    type:     annotation
    prefix:   /

message:
    resource: "@MessageBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /admin

product:
    resource: "@ProductBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
