<?php

namespace OrderBundle\Repository;

/**
 * OrderInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
